# Generated by Django 3.0.4 on 2020-04-02 10:09

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Darasa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('darasa', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, region=None)),
                ('age', models.IntegerField(default=0)),
                ('darasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='darasa_teacher', to='main.Darasa')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_teacher', to='main.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, null=True, region=None)),
                ('age', models.IntegerField(default=0)),
                ('darasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='darasa_student', to='main.Darasa')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_books', models.FileField(upload_to='pdf')),
                ('homework', models.FileField(upload_to='pdf')),
                ('exams', models.FileField(upload_to='pdf')),
                ('notes', models.FileField(upload_to='pdf')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_material', to='main.Subject')),
            ],
        ),
    ]
