# Generated by Django 3.0.4 on 2020-04-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='title',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='material',
            name='exams',
            field=models.FileField(null=True, upload_to='pdf'),
        ),
        migrations.AlterField(
            model_name='material',
            name='homework',
            field=models.FileField(null=True, upload_to='pdf'),
        ),
        migrations.AlterField(
            model_name='material',
            name='notes',
            field=models.FileField(null=True, upload_to='pdf'),
        ),
        migrations.AlterField(
            model_name='material',
            name='text_books',
            field=models.FileField(null=True, upload_to='pdf'),
        ),
    ]
