# Generated by Django 3.0.4 on 2020-05-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200504_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
    ]
