# Generated by Django 3.0.4 on 2020-04-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200402_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='exams',
            field=models.FileField(default=None, null=True, upload_to='pdf'),
        ),
        migrations.AlterField(
            model_name='material',
            name='homework',
            field=models.FileField(default=None, null=True, upload_to='pdf'),
        ),
        migrations.AlterField(
            model_name='material',
            name='notes',
            field=models.FileField(default=None, null=True, upload_to='pdf'),
        ),
    ]
