# Generated by Django 3.0.4 on 2020-05-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200504_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='ancwer',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
