# Generated by Django 3.0.4 on 2020-05-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_assignment_ancwer'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
