# Generated by Django 3.0.4 on 2020-04-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200402_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='exams',
            field=models.FileField(blank=True, default=None, upload_to='pdf'),
        ),
        migrations.AlterField(
            model_name='material',
            name='homework',
            field=models.FileField(blank=True, default=None, upload_to='pdf'),
        ),
        migrations.AlterField(
            model_name='material',
            name='notes',
            field=models.FileField(blank=True, default=None, upload_to='pdf'),
        ),
        migrations.AlterField(
            model_name='material',
            name='text_books',
            field=models.FileField(blank=True, default=None, upload_to='pdf'),
        ),
    ]
