# Generated by Django 3.0.4 on 2020-05-04 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_assignment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='ancwer',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='question',
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Assignment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=120)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Ancwer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancwer', models.CharField(max_length=120)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Question')),
            ],
        ),
    ]
