# Generated by Django 3.0.4 on 2020-05-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200505_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='ancwer',
            name='is_ancwer',
            field=models.BooleanField(default=False),
        ),
    ]
