# Generated by Django 3.0.4 on 2020-05-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_ancwer_is_ancwer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ancwer',
            name='is_ancwer',
        ),
        migrations.AddField(
            model_name='question',
            name='is_ancwer',
            field=models.BooleanField(default=False),
        ),
    ]
