# Generated by Django 3.0.4 on 2020-05-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200505_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_ancwer',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_ancwer',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
